#ifndef GPUI_VARIATION_DEF_INCLUDED
#define GPUI_VARIATION_DEF_INCLUDED
#ifdef UNITY_PROCEDURAL_INSTANCING_ENABLED
	StructuredBuffer<float4> colorBuffer;
#endif //UNITY_PROCEDURAL_INSTANCING_ENABLED
#endif //GPUI_VARIATION_DEF_INCLUDED